easy_admin:
    site_name: 'Recyclindre'
    formats:
        datetime: 'd/m/Y h:i'
    entities:
        # List the entity class name you want to manage
        Permanence:
            class: App\Entity\Permanence
            form:
                fields:
                    - { property: 'openers', type_options: { by_reference: false} }
                    - { property: 'date', type: 'datetime' }
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
