easy_admin:
    site_name: 'Recyclindre'
    formats:
        datetime: 'd/m/Y H:i'
    entities:
        # List the entity class name you want to manage
        Composter:
            class: App\Entity\Composter
            form:
                fields:
                    - name
                    - short_description
                    - description
                    - address
                    - lat
                    - lng
        Permanence:
            class: App\Entity\Permanence
            controller: App\Controller\PermanenceComtroller
            list:
                sort: ['date', 'DESC']
                fields:
                    - id
                    - date
                    - { property: 'openers', label: 'Ouvreur(s)' }
                    - { property: eventTitle, label: 'Titre de l‘événement' }
                    - { property: 'canceled', label: 'Annulé'}
            form:
                fields:
                    - { type: 'section', label: 'Infos' }
                    - { property: 'date', type: 'datetime' }
                    - { property: 'openers', label: 'Ouvreur(s)', type_options: { by_reference: false} }
                    - { property: 'canceled', label: 'Annulé'}
                    - { property: 'composter', label: 'Composteur'}
                    - { type: 'section', label: 'Stats' }
                    - { property: nbUsers, label: 'Nombres de présents', type_options: { required: false } }
                    - { property: nbBuckets, label: 'Nombres de sots ajouté', type_options: { required: false } }
                    - { property: temperature, label: 'Température du composte', type_options: { required: false } }
                    - { type: 'section', label: 'Evénement' }
                    - { property: eventTitle, label: 'Titre de l‘événement', type_options: { required: false } }
                    - { property: eventMessage, label: 'Description',type_options: { required: false } }
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
