easy_admin:
    site_name: 'Recyclindre'
    formats:
        datetime: 'd/m/Y H:i'
    entities:
        # List the entity class name you want to manage
        Composter:
            class: App\Entity\Composter
            form:
                fields:
                    - name
                    - short_description
                    - description
                    - address
                    - lat
                    - lng
        Permanence:
            class: App\Entity\Permanence
            controller: App\Controller\PermanenceComtroller
            list:
                sort: ['date', 'DESC']
            form:
                fields:
                    - { property: 'date', type: 'datetime' }
                    - { property: 'openers', type_options: { by_reference: false} }
                    - canceled
                    - composter
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
